#!/bin/bash

# Check for config-builder
if [ ! -x "$(command -v config-builder)" ]; then
	if [ -x "$(command -v yarn)" ] && [ ! -z "$(yarn list | grep renanhangai/config-builder)" ]; then
		function config-builder {
			yarn run --silent "config-builder" "$@"
		}
	elif [ -x "$(command -v npm)" ] && [ ! -z "$(npm list --parseable | grep renanhangai/config-builder)" ]; then
		function config-builder {
			npm run --silent "config-builder" "$@"
		}
	elif [ -x "$(command -v npx)" ]; then
		function config-builder {
			npx --quiet --package "@renanhangai/config-builder" config-builder "$@"
		}
	else
		CONFIG_BUILDER_IMAGE=${CONFIG_BUILDER_IMAGE:-renanhangai/config-builder}
		function config-builder {
			local DOCKER_FLAGS="--rm -i --user $(id -u):$(id -g) -v $PWD:/config";
			if [ -n "${CONFIG_BUILDER_TTY}" ]; then
				if [ -t 1 ]; then
					DOCKER_FLAGS="${DOCKER_FLAGS} -t"
				fi
			fi
			DOCKER_FLAGS="${DOCKER_FLAGS} $(--config-builder_build-whitelist)"
			docker run ${DOCKER_FLAGS} "${CONFIG_BUILDER_IMAGE}" "$@"
		}
		function --config-builder_build-whitelist {
			while read -r line; do
				split=(${line//=/ })
				echo "${split[0]}"
			done < <(env)
			return 0;
		}
		docker pull ${CONFIG_BUILDER_IMAGE}
	fi
fi

# Get git env as needed
if [ ! -z "$CONFIG_BUILDER_ENV_GIT_REF" ]; then
	GIT_REF=$(git rev-parse HEAD)
	eval "$CONFIG_BUILDER_ENV_GIT_REF"=\"$GIT_REF\"
	export "$CONFIG_BUILDER_ENV_GIT_REF"
fi